# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lito', '0002_auto_20160403_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypoint',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
