# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lito', '0005_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypoint',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lito.Story'),
        ),
    ]
