# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lito', '0006_storypoint_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypoint',
            name='story',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lito.Story'),
            preserve_default=False,
        ),
    ]
