# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lito', '0007_auto_20160501_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypoint',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
