# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lito', '0008_storypoint_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypoint',
            name='soundcloud_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='storypoint',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
